// <auto-generated />
using DriverApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendProyectoFinal.Migrations
{
    [DbContext(typeof(DriverContext))]
    [Migration("20221111153434_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackendProyectoFinal.Domain.Driver", b =>
                {
                    b.Property<long>("driverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("driverId"), 1L, 1);

                    b.Property<string>("driverDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("driverNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("driverPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("driverId");

                    b.ToTable("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
